"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { SafeAudioEngine } from "@/tinnitus/audio/SafeAudioEngine";
import { CLINICAL_CONTENT } from "@/tinnitus/domain/config";
import { classify, evaluateSafety, recommend } from "@/tinnitus/domain/rules";
import type { AlertKey, SoundId, SoundTrialResult, TinnitusProfile, UserConsent } from "@/tinnitus/domain/types";

const STORAGE = "brisa-guided-assessment-v1";
const alerts: Array<{ id: AlertKey; label: string }> = [
  { id: "pulsatile", label: "O som acompanha o ritmo do coração ou parece uma pulsação?" }, { id: "sudden_onset", label: "O zumbido começou de forma súbita?" }, { id: "sudden_hearing_loss", label: "Houve perda ou redução súbita da audição?" }, { id: "unilateral", label: "O zumbido ocorre somente em um ouvido?" }, { id: "hearing_asymmetry", label: "Existe diferença perceptível de audição entre os ouvidos?" }, { id: "severe_vertigo", label: "Há tontura intensa, desequilíbrio importante ou vertigem?" }, { id: "neurological_symptoms", label: "Há fraqueza, dormência, alteração de fala, visão ou outro sintoma neurológico?" }, { id: "ear_pain_or_discharge", label: "Há dor forte no ouvido, secreção, sangramento ou febre?" }, { id: "recent_trauma", label: "O sintoma começou após trauma na cabeça ou exposição sonora intensa?" }, { id: "unsafe", label: "O sofrimento está provocando pensamentos de autoagressão ou dificuldade de se manter em segurança?" },
];
const emptyProfile: TinnitusProfile = { location: [], perceivedSounds: [], temporalPattern: [], durationCategory: "não sei", intensity: 5, annoyance: 5, triggers: [], reliefContexts: [], hearingProfile: "unknown", soundSensitivity: "none", somaticModulation: "unknown", impact: { sleepImpact: 0, concentrationImpact: 0, emotionalDistress: 0, hypervigilance: 0, functionalImpact: 0 }, medicationRelation: "unknown" };
const option = (value: string, label = value) => <option value={value}>{label}</option>;

export default function Home() {
  const [step, setStep] = useState(0); const [consent, setConsent] = useState<UserConsent>({ accepted: false, consentVersion: CLINICAL_CONTENT.version });
  const [selectedAlerts, setSelectedAlerts] = useState<AlertKey[]>([]); const [profile, setProfile] = useState<TinnitusProfile>(emptyProfile); const [trials, setTrials] = useState<SoundTrialResult[]>([]);
  const [playing, setPlaying] = useState<SoundId | null>(null); const [trialSound, setTrialSound] = useState<SoundId | null>(null); const audio = useRef<SafeAudioEngine | null>(null);
  const safety = useMemo(() => evaluateSafety(selectedAlerts), [selectedAlerts]); const phenotypes = useMemo(() => classify(profile, selectedAlerts), [profile, selectedAlerts]); const recommendations = useMemo(() => recommend(profile, selectedAlerts, trials), [profile, selectedAlerts, trials]);
  useEffect(() => { audio.current = new SafeAudioEngine(); try { const saved = localStorage.getItem(STORAGE); if (saved) { const data = JSON.parse(saved) as { consent?: UserConsent; profile?: TinnitusProfile; alerts?: AlertKey[]; trials?: SoundTrialResult[]; step?: number }; if (data.consent) setConsent(data.consent); if (data.profile) setProfile(data.profile); if (data.alerts) setSelectedAlerts(data.alerts); if (data.trials) setTrials(data.trials); if (data.step) setStep(data.step); } } catch { /* local save is optional */ } return () => audio.current?.dispose(); }, []);
  useEffect(() => { if (consent.accepted) localStorage.setItem(STORAGE, JSON.stringify({ consent, profile, alerts: selectedAlerts, trials, step })); }, [consent, profile, selectedAlerts, trials, step]);
  const setField = <K extends keyof TinnitusProfile>(key: K, value: TinnitusProfile[K]) => setProfile((current) => ({ ...current, [key]: value }));
  const toggle = (id: AlertKey) => setSelectedAlerts((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const toggleArray = (key: "perceivedSounds" | "temporalPattern" | "triggers" | "reliefContexts", value: string) => setProfile((current) => ({ ...current, [key]: current[key].includes(value) ? current[key].filter((item) => item !== value) : [...current[key], value] }));
  async function play(sound: SoundId) { if (playing) { audio.current?.stop(); setPlaying(null); return; } await audio.current?.play(sound); setPlaying(sound); }
  function stop() { audio.current?.stop(); setPlaying(null); }
  function saveTrial(soundId: SoundId, adverse = false) { stop(); setTrials((current) => [...current.filter((trial) => trial.soundId !== soundId), { soundId, comfort: adverse ? 0 : 7, tinnitusAwarenessDuring: adverse ? 9 : 4, annoyanceDuring: adverse ? 9 : 3, relaxation: adverse ? 0 : 6, residualImprovement: adverse ? 0 : 4, residualWorsening: adverse ? 8 : 0, adverseSymptoms: adverse ? ["desconforto informado"] : [], wouldUseAgain: !adverse, testedAt: new Date().toISOString() }]); setTrialSound(null); }
  const go = (next: number) => { stop(); setStep(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  return <main className="guided-shell"><header className="guided-header"><a className="brand" href="#top"><span className="brand-mark" aria-hidden="true"><i /><i /><i /></span><span>brisa</span></a><span>manejo sonoro guiado</span><button className="text-button" onClick={() => { localStorage.removeItem(STORAGE); setConsent({ accepted: false, consentVersion: CLINICAL_CONTENT.version }); setProfile(emptyProfile); setSelectedAlerts([]); setTrials([]); go(0); }}>Apagar dados locais</button></header>
    <section className="guided-progress" aria-label="Progresso"><span>Etapa {step + 1} de 6</span><div><i style={{ width: `${((step + 1) / 6) * 100}%` }} /></div></section>
    {step === 0 && <section className="guided-card intro-card" id="top"><span className="eyebrow"><span /> FERRAMENTA EDUCATIVA</span><h1>Encontre sons que valem ser testados com cuidado.</h1><p>Esta avaliação não diagnostica, trata ou cura zumbido. Ela usa suas respostas para sugerir opções de suporte e registrar sua resposta individual.</p><div className="notice"><strong>Antes de começar</strong><p>Interrompa qualquer som diante de dor, pressão, tontura, náusea, cefaleia ou piora. Nunca altere medicamentos por orientação do app.</p></div><label className="consent"><input type="checkbox" checked={consent.accepted} onChange={(event) => setConsent({ accepted: event.target.checked, acceptedAt: event.target.checked ? new Date().toISOString() : undefined, consentVersion: CLINICAL_CONTENT.version })} /> Li e entendi que esta ferramenta é educativa e que sons podem ajudar algumas pessoas e piorar outras.</label><button className="primary-action" disabled={!consent.accepted} onClick={() => go(1)}>Iniciar avaliação</button></section>}
    {step === 1 && <section className="guided-card"><span className="eyebrow"><span /> TRIAGEM DE SEGURANÇA</span><h2>Há algum sinal que merece avaliação antes de testar sons?</h2><p className="muted">Marque apenas as situações presentes. Você pode concluir a avaliação sem ouvir nenhum áudio.</p><div className="question-list">{alerts.map((item) => <label key={item.id}><input type="checkbox" checked={selectedAlerts.includes(item.id)} onChange={() => toggle(item.id)} /> {item.label}</label>)}</div>{safety.blocked ? <div className="block-message"><strong>Vamos pausar os testes sonoros.</strong>{safety.reasons.map((reason) => <p key={reason}>{reason}</p>)}<p>Procure atendimento apropriado. O Brisa não exibirá recomendações sonoras personalizadas nesta situação.</p></div> : <div className="actions"><button className="secondary-action" onClick={() => go(0)}>Voltar</button><button className="primary-action" onClick={() => go(2)}>Continuar</button></div>}</section>}
    {step === 2 && <section className="guided-card"><span className="eyebrow"><span /> CARACTERÍSTICAS</span><h2>Como o zumbido se apresenta?</h2><Fieldset title="Onde você percebe o som?" values={profile.location} options={["ouvido esquerdo", "ouvido direito", "ambos os ouvidos", "centro da cabeça", "localização variável", "não sei"]} onChange={(value) => setField("location", profile.location.includes(value) ? profile.location.filter((item) => item !== value) : [...profile.location, value])} /><Fieldset title="Qual descrição combina mais?" values={profile.perceivedSounds} options={["apito", "tom eletrônico", "chiado", "estática", "cigarra", "assobio", "motor", "ronco", "vento", "cachoeira", "clique", "estalo", "múltiplos sons", "não sei"]} onChange={(value) => toggleArray("perceivedSounds", value)} /><Fieldset title="Qual é o padrão?" values={profile.temporalPattern} options={["contínuo", "intermitente", "pulsante", "flutuante", "aparece em crises", "muda durante o dia"]} onChange={(value) => toggleArray("temporalPattern", value)} /><div className="range-grid"><Range label="Volume percebido" value={profile.intensity} onChange={(value) => setField("intensity", value)} /><Range label="Incômodo" value={profile.annoyance} onChange={(value) => setField("annoyance", value)} /></div><div className="actions"><button className="secondary-action" onClick={() => go(1)}>Voltar</button><button className="primary-action" onClick={() => go(3)}>Continuar</button></div></section>}
    {step === 3 && <section className="guided-card"><span className="eyebrow"><span /> PERFIL E IMPACTO</span><h2>O que merece mais atenção agora?</h2><div className="form-grid"><label>Perfil auditivo<select value={profile.hearingProfile} onChange={(event) => setField("hearingProfile", event.target.value as TinnitusProfile["hearingProfile"])}>{option("unknown", "Não sei")} {option("no_known_hearing_loss", "Sem perda conhecida")} {option("suspected_hearing_loss", "Suspeita de perda")} {option("confirmed_hearing_loss", "Perda confirmada")} {option("uses_hearing_aid", "Usa aparelho auditivo")}</select></label><label>Sensibilidade a som<select value={profile.soundSensitivity} onChange={(event) => setField("soundSensitivity", event.target.value as TinnitusProfile["soundSensitivity"])}>{option("none", "Nenhuma")} {option("mild", "Leve")} {option("moderate", "Moderada")} {option("severe", "Severa")} {option("reactive_tinnitus", "Zumbido reativo")}</select></label><label>Alteração com mandíbula/pescoço<select value={profile.somaticModulation} onChange={(event) => setField("somaticModulation", event.target.value as TinnitusProfile["somaticModulation"])}>{option("unknown", "Não sei")} {option("none", "Não")} {option("jaw", "Mandíbula")} {option("neck", "Pescoço")} {option("touch", "Toque")} {option("multiple", "Mais de um")}</select></label><label>Relação temporal com medicamento<select value={profile.medicationRelation} onChange={(event) => setField("medicationRelation", event.target.value as TinnitusProfile["medicationRelation"])}>{option("unknown", "Não sei")} {option("no_clear_relation", "Sem relação clara")} {option("started_before_tinnitus", "Começou antes do zumbido")} {option("dose_increased_before_tinnitus", "Aumento de dose antes")}{option("withdrawal_before_tinnitus", "Interrupção antes")}</select></label></div><p className="small-note">Uma possível relação temporal não confirma causa. Não interrompa ou altere medicamentos sem o profissional responsável.</p><div className="range-grid">{([ ["sleepImpact", "Sono"], ["concentrationImpact", "Concentração"], ["emotionalDistress", "Sofrimento emocional"], ["hypervigilance", "Atenção constante ao som"], ["functionalImpact", "Impacto nas atividades"] ] as const).map(([key, label]) => <Range key={key} label={label} value={profile.impact[key]} onChange={(value) => setProfile((current) => ({ ...current, impact: { ...current.impact, [key]: value } }))} />)}</div><div className="actions"><button className="secondary-action" onClick={() => go(2)}>Voltar</button><button className="primary-action" onClick={() => go(4)}>Ver opções</button></div></section>}
    {step === 4 && <section className="guided-card"><span className="eyebrow"><span /> RESULTADO PERSONALIZADO</span><h2>Sons potencialmente mais adequados para serem testados com segurança neste perfil.</h2>{safety.referral && <div className="notice"><strong>Avaliação profissional recomendada.</strong><p>Enquanto isso, apenas sons genéricos de baixo risco são mostrados. Tons e ruído de banda estreita ficam bloqueados.</p></div>}<p className="muted">Perfis compatíveis: {phenotypes.join(", ").replaceAll("_", " ")}. Isso não é um diagnóstico.</p><div className="recommendations">{recommendations.filter((item) => !item.excluded).slice(0, 3).map((item) => <article key={item.soundId}><div><span className={item.evidenceLevel === "limited" ? "tag experimental" : "tag"}>{item.evidenceLevel === "limited" ? "Evidência limitada" : "Opção de suporte"}</span><h3>{item.name}</h3><p>{item.reasons[0]}</p><small>{item.cautions[0]}</small></div><button className="secondary-action" onClick={() => { setTrialSound(item.soundId); go(5); }}>Testar</button></article>)}</div><p className="small-note">Essas opções buscam conforto, redução do contraste com silêncio e relaxamento; não prometem diminuir o volume físico percebido ou curar o sintoma.</p><div className="actions"><button className="secondary-action" onClick={() => go(3)}>Ajustar respostas</button><button className="primary-action" onClick={() => go(5)}>Ir para teste comparativo</button></div></section>}
    {step === 5 && <section className="guided-card"><span className="eyebrow"><span /> TESTE CONTROLADO</span><h2>Teste um som de cada vez.</h2><p className="muted">Faça em local seguro, sem dirigir ou operar máquinas. Comece no menor volume audível. O áudio não inicia sozinho.</p><button className="stop-button" onClick={stop} disabled={!playing}>■ Parar áudio agora</button><div className="trial-grid">{recommendations.filter((item) => !item.excluded).slice(0, 5).map((item) => <article key={item.soundId} className={trialSound === item.soundId ? "trial active" : "trial"}><h3>{item.name}</h3><p>{CLINICAL_CONTENT.sounds[item.soundId].description}</p><button className="primary-action" onClick={() => { setTrialSound(item.soundId); void play(item.soundId); }}>{playing === item.soundId ? "Pausar" : "Ouvir por pouco tempo"}</button>{trialSound === item.soundId && <div className="trial-feedback"><strong>Como foi sua resposta?</strong><button onClick={() => saveTrial(item.soundId)}>Confortável / usaria novamente</button><button className="danger" onClick={() => saveTrial(item.soundId, true)}>Houve piora ou desconforto</button></div>}</article>)}</div>{trials.length > 0 && <div className="notice"><strong>Registros salvos localmente.</strong><p>Suas próximas recomendações consideram conforto e piora relatados. Sons com piora relevante são removidos dos testes automáticos.</p></div>}<div className="actions"><button className="secondary-action" onClick={() => go(4)}>Voltar ao resultado</button><button className="primary-action" onClick={() => go(4)}>Atualizar resultado</button></div></section>}
    <footer>Dados ficam neste dispositivo. Versão de regras: {CLINICAL_CONTENT.version}. Esta ferramenta não substitui avaliação profissional.</footer></main>;
}

function Fieldset({ title, values, options, onChange }: { title: string; values: string[]; options: string[]; onChange: (value: string) => void }) { return <fieldset><legend>{title}</legend><div className="pill-list">{options.map((value) => <label key={value} className={values.includes(value) ? "pill selected" : "pill"}><input type="checkbox" checked={values.includes(value)} onChange={() => onChange(value)} />{value}</label>)}</div></fieldset>; }
function Range({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="range"><span>{label}<b>{value}/10</b></span><input type="range" min="0" max="10" value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }
